title: "Fields of the World - Inference API"
description: "A service for field boundary inference from satellite images."
version: "0.1.0"

server:
  host: "0.0.0.0"
  port: 8000
  debug: false
  database_url: "sqlite:///./data/ftw_inference.db"
  cors:
    origins: ["*"]  # Allow all origins (CORS)

security:
  auth_disabled: false  # Set to true to disable authentication
  secret_key: "your_secret" # Secret key for JWT token signing
  access_token_expire_minutes: 30  # Token expiration time in minutes

# Models configuration
models:
  - id: 2_Class_FULL_FTW_Pretrained
    title: FTW v1 / 2-Class / Full
    description: 2-Class model trained on the full FTW dataset for field boundary inference
    license: proprietary
    version: v1
    file: 2_Class_FULL_FTW_Pretrained.ckpt
  - id: 2_Class_CCBY_FTW_Pretrained
    title: FTW v1 / 2-Class / CC-BY
    description: 2-Class model trained on a limited FTW dataset for field boundary inference
    license: CC-BY-4.0
    version: v1
    file: 2_Class_CCBY_FTW_Pretrained.ckpt
  - id: 3_Class_FULL_FTW_Pretrained
    title: FTW v1 / 3-Class / Full
    description: 3-Class model trained on the full FTW dataset for field boundary inference
    license: proprietary
    version: v1
    file: 3_Class_FULL_FTW_Pretrained.ckpt
  - id: 3_Class_CCBY_FTW_Pretrained
    title: FTW v1 / 3-Class / CC-BY
    description: 3-Class model trained on a limited FTW dataset for field boundary inference
    license: CC-BY-4.0
    version: v1
    file: 3_Class_CCBY_FTW_Pretrained.ckpt
