name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest # ignore for now
          # - windows-latest # ignore for now
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
          # - '3.13' # doesn't work yet
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r server/requirements.txt
        pip install pytest pytest-cov pre-commit

    - name: Lint and format check with pre-commit
      uses: pre-commit/action@v3.0.0

    - name: Run tests
      run: |
        cd server
        pytest -v --cov=server
